AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for cross account access from the client account to the CloudTrek Customers account
Parameters:
  RoleName:
    Description: The name for the IAM Role
    Type: String
    Default: CloudTrekAdmin
  AccountID:
    Description: The ID of the AWS Account to add in the CrossAccount setup
    Type: String
    Default: 077134902660
  AttachedPolicy:
    Description: The policy to attach the CloudTrek Cross Account IAM role
    Type: String
    Default: AdministratorAccess
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            AWS: !Join ["", [ "arn:aws:iam::", !Ref AccountID, ":root" ] ]
          Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - Fn::Join:
        - ''
        - - arn:aws:iam::aws:policy/
          - Ref: AttachedPolicy
      RoleName:
        Ref: RoleName
Outputs:
  RoleARN:
    Description: The ARN of the role that can be assumed by the other account.
    Value:
      Fn::GetAtt:
      - Role
      - Arn
  SwitchAccountLink:
    Description: The link provided for use when switching from one account to the
      other
    Value:
      Fn::Join:
      - ''
      - - https://signin.aws.amazon.com/switchrole?account=
        - Ref: AWS::AccountId
        - "&roleName="
        - Ref: RoleName